
services:
  backend:
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app
      - /app/node_modules
  
  frontend:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
      - /app/node_modules